spring.application.name=api_sistema_hospitalar
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.url=jdbc:postgresql://dpg-d6olkkvafjfc7389d9v0-a.oregon-postgres.render.com:5432/dbhospital_g5li?sslmode=require
#spring.datasource.username=postgres
#spring.datasource.password=aluno
spring.datasource.username=admin
spring.datasource.password=0wCPVm25ZPovuSZn7PunuAL2O8O9MZsG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
springdoc.swagger-ui.path=/api_sistema_hospitalar/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true